### PR TITLE
perf: reduce image size

### PR DESCRIPTION
**Pull request by ftapajos**
Creates a different target for extracting the zip file

### CODE REVIEW

**Comment by Linjieqiang** [comment]
Good~ @xanderhendriks  Could you see see? Because the docker image size is so big now.

**Review by xanderhendriks — APPROVED** [review]

**Comment by xanderhendriks** [comment]
It took me some time to look into this. I had never used multi stage builds before, so I first wanted to understand what's happening.
The image is being pushed to Docker now.
How do you guys use this docker? Do you create it locally from the Dockerfile or pull from the Docker website? And are you also using the [action-build-stm32cubeide](https://github.com/xanderhendriks/action-build-stm32cubeide)? If so, then I can also update that one to point to the new docker. Otherwise, I'll just leave it to the next STM CubeIde release.

**Comment by Linjieqiang** [comment]
image
I use your image to make my own embedded development image. Thank you for your dedication and continuous maintenance.

**Comment by Linjieqiang** [comment]
By the way, ubuntu 24.04 is ready to use. 

`ARG IMAGE=ubuntu:22.04` -> `ARG IMAGE=ubuntu:24.04` ?

@xanderhendriks

**Comment by xanderhendriks** [comment]
Thanks for the feedback. And I'll update the Ubuntu version with the next update of the action.

**Comment by Linjieqiang** [comment]
image
@xanderhendriks OK. Now the newest version is v1.16.1, so you can try.

**Pull request merged**
